### ISSUE TITLE
Setting up Jacoco plugin for SonarQube for code coverage reports

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#158]
SonarQube does not provide code coverage reports by default. In order to get a report for code coverage, we must set up the Jacoco plugin in order to obtain XML reports for the code coverage.

**Comment by jaychenblue** [comment]
JaCoCo is also needed for the testing report. Jun and I have tried unsuccessfully in setting up JaCoCo by itself. There seems to be an issue with gradle.

**Comment by JenYn** [comment]
One of the (many) tutorials followed: https://medium.com/@vialyx/android-code-coverage-metrics-with-sonarqube-jacoco-3f99bc700e84

**Comment by jaychenblue** [comment]
The Gradle error message was resolved. Maybe setting up JaCoCo will work this time.

**Comment by JenYn** [comment]
Now that the Gradle error message was resolved (#161), I will retry to setup the jacoco plugin for SonarQube.

**Comment by JenYn** [comment]
Still no luck.
Constantly getting error messages. I believe that the problem might be our gradle version, however every time I change it, I get a new error.

Currently following this: https://stackoverflow.com/questions/37086806/android-studio-failed-to-apply-plugin-id-com-android-application

**Comment by JenYn** [comment]
It is important to note that Android Gradle plugin is not the same as Gradle.
We must therefore not change the dependency
https://stackoverflow.com/questions/37086806/android-studio-failed-to-apply-plugin-id-com-android-application

**Comment by JenYn** [comment]
Error we keep getting: 
![image](https://user-images.githubusercontent.com/26283932/77315580-29ea9380-6cde-11ea-9cc2-20c1fcd0aac4.png)

**Comment by JenYn** [comment]
![image](https://user-images.githubusercontent.com/26283932/77318926-4e496e80-6ce4-11ea-997c-1d0f76e03395.png)

**Comment by vicmanea** [comment]
I have created an issue with this specific error in mind, it can be found here:
https://github.com/gradle/gradle/issues/12609

**Comment by JenYn** [comment]
After contacting the TA (Mossabir), we will create a new branch called jacoco-setup-v2 and follow the tutorial he sent us. 
https://android.jlelse.eu/android-quality-with-mvp-espresso-junit-jacoco-and-sonarqube-3430d9ee4a4a

**Comment by JenYn** [comment]
Following this https://community.sonarsource.com/t/coverage-test-data-importing-jacoco-coverage-report-in-xml-format/12151

**Comment by JenYn** [comment]
We are getting a report, however it is not accurate:
![image](https://user-images.githubusercontent.com/26283932/77709866-c644bc80-6fa2-11ea-8679-af645de7d854.png)

![image](https://user-images.githubusercontent.com/26283932/77709876-cd6bca80-6fa2-11ea-93cf-80669f79fe1b.png)

**Comment by JenYn** [comment]
This configuration only works on Windows. If you have a mac, it will not work. 

To generate the test coverage report, run the following command in the terminal:
 ./gradlew jacocoTestReportDebug

The report will be found here: scout-concordia\app\build\reports\jacoco\debug\index.html
